### PR TITLE
Add support for musl wheels

### LINKED ISSUE #391: Add wheels for musl linux
Hi, first let me thank you for your awesome work.

Is it possible to add musllinux wheel builds to pypi ([PEP656](https://www.python.org/dev/peps/pep-0656/))?

This would be great for all alpine users since it would simplify and speed up the installation of the libsass package.

### PR DESCRIPTION
**Pull request by ObserverOfTime**
This closes #391. I've tested the musl wheel on Alpine edge and it works.

~~It might be worth creating a new release if and when this PR is merged.
Both this change and the Python 2 removal (d333e3c419f48f4b2d96528cb4c83db1f02adaec) are quite important.~~

### CODE REVIEW

**Comment by asottile** [comment]
please don't touch unrelated files

**Comment by ObserverOfTime** [comment]
OK, I'll let you fix those yourself.

**Comment by asottile** [comment]
is this image official? I can't find any docs for it

**Comment by ObserverOfTime** [comment]
It's official. It was added in pypa/manylinux#1135.

**Comment by asottile** [comment]
it's undocumented so I would prefer to wait until the linked issue there is resolved before depending on undocumented behavior

**Comment by ObserverOfTime** [comment]
So, it's fine to depend on a deprecated image (`manylinux1`) but not an undocumented one?

**Comment by ObserverOfTime** [comment]
The "undocumented" image is already used by [pypa/cibuildwheel](https://github.com/pypa/cibuildwheel). There's really no reason not to depend on it.

**Comment by ObserverOfTime** [comment]
Would you accept a pull request that builds the wheels with cibuildwheel on GitHub actions instead?

**Comment by ObserverOfTime** [comment]
I'll take that as a no.

**Pull request closed without merging**
