### PR TITLE
Upgrade to 3.4.9

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by asottile** [comment]
yay, sourcemaps changed -- this makes sense now that they're unicode aware (reading through changelogs) -- I'll go update them

**Comment by asottile** [comment]
hrmmm though segfault on posix -- seems like there might be an upstream bug here... trying to get a trace...

**Comment by asottile** [comment]
trying to get a core dump but not doing so well -- I'm not on my usual computer.

@xzyfer just in case it is actually a problem -- we're seeing segfaults with 3.4.9 that we weren't seeing with 3.4.8 -- I'll try and make a minimal reproduction

**Comment by xzyfer** [comment]
cc @mgreter who is managing 3.4.x releases

**Comment by mgreter** [comment]
I had to delete the tag first since I saw the same error on perl-libsass (it was maybe up for 30 minutes). Are you sure you have https://github.com/sass/libsass/commit/6de5050d11a1789d9922eb24e2925047ecbb499b included?

**Comment by asottile** [comment]
ah nice -- I was too quick!  I'll try again with the new tag -- thanks 🎉

**Comment by mgreter** [comment]
Cool, I guess we should add some tests in libsass directly to catch these errors.
Unfortunately SassC doesn't use the more advanced API features ...

**Comment by asottile** [comment]
awesome -- let me know if you'd like some help with that :)

**Comment by mgreter** [comment]
IMO we would need something like https://github.com/sass/libsass/blob/master/docs/api-function-example.md for travis and appveyor to test custom functions/importers directly. I don't see any other easy way to cover this in our CI otherwise. If you can come up with a PR that would be great ;)

**Comment by asottile** [comment]
I'll see what I can cook up in my _copious_ amounts of freetime, I've added it to the top of my "todo" list :)

**Pull request merged**
